Fix error when loading big module
telethon.errors.rpcerrorlist.MediaCaptionTooLongError: The caption is too long (caused by EditMessageRequest)
When loading module, that contains the description, that doesn't fit in 2048 characters.